title: "Ge Li (Bruce)"
author: "Ge Li"
description: "Ge Li (Bruce)'s website. All rights reserved."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: CV, url: "https://drive.google.com/file/d/1vHGIhmXDZhT4hYtLZx5mtMDNTLf5Ccd8/view?usp=sharing"}
  - {title: Mail, icon: envelope, url: "mailto:ge.li@kit.edu" }
  - {title: Github, icon: github, url: "https://github.com/BruceGeLi" }
  - {title: Google Scholar, icon: google-scholar, url: "https://scholar.google.com/citations?user=ahqtghsAAAAJ&hl=en" }
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/geli-bruce/" }

#external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
#  - {title: Mail, icon: envelope, url: "mailto:ge.li@kit.edu"}
#  - {title: Github, icon: github, url: "https://github.com/BruceGeLi"}
#  - {title: CV, icon: cv, url: "https://drive.google.com/file/d/1vHGIhmXDZhT4hYtLZx5mtMDNTLf5Ccd8/view?usp=drive_link"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
